import type { CategoryId } from "./game.types";

type PlayableCategoryId = Exclude<CategoryId, "mix">;

export const categoryLabels: Record<CategoryId, string> = {
  mix: "Tout mélanger",
  objects: "Objets",
  animals: "Animaux",
  food: "Cuisine",
  places: "Lieux",
  jobs: "Métiers",
  leisure: "Loisirs",
};

export const wordsByCategory: Record<PlayableCategoryId, readonly string[]> = {
  objects: [
    "Parapluie",
    "Boussole",
    "Grille-pain",
    "Valise",
    "Oreiller",
    "Télécommande",
    "Cadenas",
    "Brosse à dents",
    "Bougie",
    "Casque audio",
    "Tire-bouchon",
    "Réveil",
    "Aspirateur",
    "Trombone",
    "Lampe torche",
    "Thermomètre",
    "Échelle",
    "Miroir",
    "Clé USB",
    "Agrafeuse",
    "Ventilateur",
    "Sac à dos",
    "Marteau",
    "Jumelles",
  ],
  animals: [
    "Panda",
    "Girafe",
    "Dauphin",
    "Hérisson",
    "Caméléon",
    "Pieuvre",
    "Paresseux",
    "Flamant rose",
    "Loutre",
    "Koala",
    "Manchot",
    "Écureuil",
    "Hippopotame",
    "Méduse",
    "Perroquet",
    "Rhinocéros",
    "Hibou",
    "Kangourou",
    "Crabe",
    "Moustique",
    "Autruche",
    "Castor",
    "Lézard",
    "Baleine",
  ],
  food: [
    "Croissant",
    "Raclette",
    "Sushi",
    "Tiramisu",
    "Guacamole",
    "Crêpe",
    "Pop-corn",
    "Lasagnes",
    "Fondue",
    "Baguette",
    "Cheesecake",
    "Couscous",
    "Omelette",
    "Limonade",
    "Hot-dog",
    "Mousse au chocolat",
    "Kebab",
    "Gaufre",
    "Paella",
    "Soupe à l’oignon",
    "Macaron",
    "Burrito",
    "Pizza",
    "Salade de fruits",
  ],
  places: [
    "Aéroport",
    "Bibliothèque",
    "Camping",
    "Phare",
    "Musée",
    "Plage",
    "Château",
    "Supermarché",
    "Stade",
    "Gare",
    "Forêt",
    "Cinéma",
    "Hôpital",
    "Désert",
    "Parc d’attractions",
    "Restaurant",
    "Piscine",
    "Montagne",
    "Boulangerie",
    "Zoo",
    "Île déserte",
    "Marché",
    "Salle de sport",
    "Aquarium",
  ],
  jobs: [
    "Astronaute",
    "Boulanger",
    "Pompier",
    "Architecte",
    "Vétérinaire",
    "Magicien",
    "Pilote",
    "Jardinier",
    "Photographe",
    "Journaliste",
    "Dentiste",
    "Développeur",
    "Cuisinier",
    "Professeur",
    "Plombier",
    "Avocat",
    "Coiffeur",
    "Facteur",
    "Réalisateur",
    "Musicien",
    "Libraire",
    "Guide touristique",
    "Scientifique",
    "Serveur",
  ],
  leisure: [
    "Karaoké",
    "Randonnée",
    "Jeu vidéo",
    "Jardinage",
    "Poterie",
    "Surf",
    "Photographie",
    "Pêche",
    "Yoga",
    "Danse",
    "Lecture",
    "Escalade",
    "Pique-nique",
    "Cinéma",
    "Bowling",
    "Échecs",
    "Cuisine",
    "Voyage",
    "Dessin",
    "Concert",
    "Vélo",
    "Piano",
    "Natation",
    "Théâtre",
  ],
};

export const playableCategoryIds = Object.keys(wordsByCategory) as PlayableCategoryId[];
